### PR TITLE
Variable hintname length

### PR DESCRIPTION
**Pull request by orangenschalen**
This branch enables hint names with varied length. If a longer name uses a shorter one as a prefix, the shorter ones are not used.

### CODE REVIEW

**Comment by johnbeard** [comment]
I think the hinting strategy should be configurable between strategies (and also in hint char selection and styling).

**Comment by bovine3dom** [comment]
@johnbeard hintchars are configurable already.

I had a brief look at this and it seems to just be better; it removes the needless extra characters that we currently have.

I am fully in favour of "select hint by typing name" being an option to choose.

Thanks @orangenschalen, cmcaine or myself will review this properly soon!

**Comment by orangenschalen** [comment]
I'd like to remove one superfluous line from my changes, and to change my author information. Should I (--force) replace the contents of this pull request's branch or should I start a new one?

As this is my first GitHub pull request, I'm completely unaware of the established local habits.

**Comment by bovine3dom** [comment]
I think `--force` is fine, so long as you tell people first. Sorry that we haven't got around to merging/reviewing it yet.

**Comment by orangenschalen** [comment]
Okay, I've removed the line in question and my author information is as intended as well. The branch is now as intended.

Please feel free to review and nag or merge.

**Comment by bovine3dom** [comment]
@orangenschalen 
> If a longer name uses a shorter one as a prefix, the shorter ones are not used.

Experimentally, this is not the case on, e.g, http://www.bbc.co.uk/news: J and JJ will appear as hints.

In fact, the code seems to just ensure that "H" never appears as a hint.

Could you look into this? Thanks!

**Comment by orangenschalen** [comment]
Now it should work as advertised.

It's my first 3 days with typescript...

**Comment by bovine3dom** [comment]
Thanks, it works now.

The `hintchars` setting seems to be ignored, though - e.g. `set hintchars 12345`. Do you have time to investigate that?

**Comment by orangenschalen** [comment]
The hintchars setting works for me with the branch. Could you double check please?

**Comment by bovine3dom** [comment]
OK. `web-ext` was misbehaving for me just after I checked so the problem could well be at my end. Thanks for your patience!

**Comment by bovine3dom** [comment]
Yeah, it works. I'll remove the setting for `hintorder` and merge. Thanks!

**Comment by orangenschalen** [comment]
Thank you as well!

**Pull request merged**
