### PR TITLE
Implement :bufferall

### PR DESCRIPTION
**Pull request by glacambre**
This fixes https://github.com/cmcaine/tridactyl/issues/62 . It works on my tiling window manager, I couldn't test whether it worked on Windows/OSX.
Should we bind `b` to `:bufferall` rather than `:buffer`? I think it'd make sense.

### CODE REVIEW

**Comment by bovine3dom** [comment]
Couple of comments from just using it:

`bufferall` on its own (i.e. `:bufferall<CR>`) gives an error - I think it should probably just try to open the current tab.

I think I would like to see the buffer IDs being WINDOW_ID.BUFFER_ID e.g. 1.1, 1.2, 2.1 etc.

I disagree with `Should we bind b to :bufferall rather than :buffer? I think it'd make sense.`; I think binding it to `B` would be nicer.

**Comment by bovine3dom** [comment]
Also, you seem to have copied the `open` completion logic rather than `buffer`, which leads to the following strange behaviour:

- with small window sizes, the right hand side of the completion window is blank, presumably waiting for a URL that never comes
- the most likely buffer is not automatically selected as you type, so `bufferall trid<CR>` gives you an error rather than switching to the tab that contains Tridactyl.

**Comment by glacambre** [comment]
>Also, you seem to have copied the open completion logic rather than buffer
Nope, I copied the `buffer` completion classes. I get the same behavior for `open`, `buffer` and `bufferall` when the window is small (right hand side not being displayed).

The reason why the most likely completion option wasn't selected is that I didn't re-implement the `setStateFromScore` function. This is fixed now.

**Comment by glacambre** [comment]
I moved each CompletionSource+CompletionOption combination to its own file in order to make working with them a bit easier. Let me know if you think this was a bad idea.

**Comment by bovine3dom** [comment]
There's something strange going on with the tab ID's. If I have two windows, `bufferall 2.1` completes to nothing and gives me the error `# Error: Incorrect argument types for tabs.get. `. Expected behaviour: first tab of second window is opened.

**Comment by glacambre** [comment]
Oh, I misunderstood what your meant by having the buffer IDs be `WINDOW_ID.BUFFER_ID`. I thought this was purely for aesthetic reasons, so `bufferall` still expects a firefox tab ID. I'll fix this.

**Comment by bovine3dom** [comment]
@glacambre doesn't seem to work. `bufferall 2.1` opens 1.1, 1.1 opens 2.1, 1.2 opens 2.1. Just generally it's all a bit muddled up.

**Comment by glacambre** [comment]
I can't seem to reproduce this issue. Does running `jsb bufferall("1.2")` correctly selects the second tab of the first window? If yes I think your problem might come from the fuzzy selection algorithm selecting the wrong option?

**Comment by bovine3dom** [comment]
The correct tab was highlighted each time by completions which is why I was so confused. I'll look into it again later today.

**Comment by bovine3dom** [comment]
Could not reproduce :S

**Pull request merged**
