### PR TITLE
Hints: do not force uppercase display of hintchars

### PR DESCRIPTION
**Pull request by Blatinox**
Those 2 commits allows to use both uppercase and lowercase hintchars.

Please see pr #130 for the origin of this pr.

### CODE REVIEW

**Comment by bovine3dom** [comment]
Thanks for this PR!

I would prefer the CSS to remain uppercase unless an uppercase letter is in `hintchars`. Is that something you would be able and happy to do?

**Comment by Blatinox** [comment]
What's the interest of keeping the uppercase property in CSS ? My main idea is to add the possibility to display hintchars in lowercase, not only to allow both lowercase and uppercase in `hintchars`.

**Comment by bovine3dom** [comment]
As I said in #130, I think the hints are easier to read in all caps. It's how most similar extensions do it.

I'm happy for you to add a setting that turns off the uppercase CSS in all cases.

**Comment by Blatinox** [comment]
I understand, that's why by default my PR keeps the uppercase. It only moves it away from the CSS so it's easier to change characters.

What do you think about the first commit of this PR that allows to press Shift while entering the hint key ?

**Comment by bovine3dom** [comment]
@Blatinox sorry for the delay in getting back to you. I hadn't realised you had replied.

I'm happy for this to go in with the proviso that hintchars should be displayed in uppercase when there are no uppercase hintchars, but as soon as there is an uppercase hintchar they are displayed in mixed case.

**Comment by bovine3dom** [comment]
Closing as #481 / some theme API will allow people to style the hints however they please.

**Pull request closed without merging**
