### PR TITLE
Implement smoothscroll

### PR DESCRIPTION
**Pull request by glacambre**
This is a temporary fix for https://github.com/cmcaine/tridactyl/issues/54 until we figure how to read user preferences either through the native messenger of through Firefox's debugging protocol.
Note that this doesn't seem to work for websites with frames.

### CODE REVIEW

**Comment by bovine3dom** [comment]
Thanks for looking into this.

I'd like to try to figure out why it's not working on more websites.

If I paste this snippet into the web console:

```js
document.getRootNode().all[0].style.scrollBehavior = "smooth"
```

smooth scrolling seems to work on all the sites I've tried it on.


Replacing all of your relevant lines with 

```ts
 ;(document as any).getRootNode().all[0].style.scrollBehavior = "smooth"
```

doesn't work, though. I've tried logging the document, and as far as I can tell it is exactly the same as the document accessible in the console.


Do you have any ideas?

**Comment by glacambre** [comment]
This makes absolutely no sense. I'm testing my code on http://www.angelfire.com/super/badwebs/ .
The following code won't work when the page is loaded. However it'll work if you update your smoothscroll setting after the page has been loaded.
```ts
config.getAsync("smoothscroll").then(smooth => {
    let rec = (doc, smooth) => {
        // Take all elements
        Array.from(doc.querySelectorAll("*")).forEach((elem) => {
            // Make them smooth or reset them
            (elem as any).style.scrollBehavior = smooth ? "smooth" : "auto"
            // If the element is a frame
            if (elem instanceof HTMLFrameElement || elem instanceof HTMLIFrameElement) {
                // If the frame is loaded, do the same with its children
                if (elem.contentDocument.readyState == "complete") {
                    rec(elem.contentDocument, smooth)
                } else {
                    // Otherwise, add a listener that will do the same once the frame is loaded
                    console.log(elem.contentDocument, "readystate =" + elem.contentDocument.readyState)
                    elem.contentDocument.addEventListener("readystatechange", ev => {
                        console.log(ev)
                        rec(elem.contentDocument, smooth)
                    })
                }
            }
        })
    }
    browser.storage.onChanged.addListener((changes, areaname) => {
        if (areaname == "sync") {
            let oldSmooth = changes.userconfig.oldValue.smoothscroll
            let newSmooth = changes.userconfig.newValue.smoothscroll
            if (oldSmooth != newSmooth)
                rec(document, newSmooth === "true")
        }
    })
    if (document.readyState == "complete")
        rec(document, smooth === "true")
    else
        window.addEventListener("DOMContentLoaded", () => {
            rec(document, smooth === "true")
        })
})
```
The console shows three frames, each with `readystate = uninitialized`. If you call the code once the page has been loaded, `readystate` will be set to `complete` and yet the readystatechange event is never triggered!
I'll keep looking into it but I'm starting to think this is a Firefox bug.

**Comment by glacambre** [comment]
520667e makes smoothscroll work on http://www.angelfire.com/super/badwebs/ but now every element is scrolled at the same time. This is crazy.

**Comment by glacambre** [comment]
RecursiveScroll scrolls everything probably because smooth scrolling is asynchronous or something. There's still a small hack I can try but I'm starting to think that the only way forward is to re-implement scrolling ourselves, like the [vim-vixen dev did](vim-vixen/src/content/scrolls.js).

**Comment by bovine3dom** [comment]
I think we should avoid that if it's at all possible.

I suspect the problem is in recursive scroll; I think our scrolling logic needs some more thought. Really, I want to just scroll the biggest element on the page unless I move focus elsewhere.

**Comment by glacambre** [comment]
>I suspect the problem is in recursive scroll; I think our scrolling logic needs some more thought

I agree, but I can't come up with something satisfying.

>Really, I want to just scroll the biggest element on the page unless I move focus elsewhere

Half of this is already happening since `document.documentElement` is the biggest element on the page :^). I don't think our algorithm can be as simple as that. We don't want to scroll large elements that aren't visible, it doesn't always make more sense to scroll the largest element (e.g. if a page contains a small scrollable div I want this div to be scrolled when it is visible before I continue scrolling the "main page element").

6b44f86 makes smooth scrolling work on both http://www.angelfire.com/super/badwebs/ and normal pages and I think it's the best I can do. But scrolling by keeping `j` pressed looks really awful.

**Comment by bovine3dom** [comment]
I'm finding that scrolling is really slow and laggy with `smoothscroll true` compared to pressing the down arrow with Firefox smooth scrolling.

Additionally, on news.ycombinator.com, scrolling down with smoothscroll on only scrolls a couple of pixels or so at a time, even just by doing document.documentElement.style.scrollBehavior = "smooth".

So, maybe we should just make our own smooth scrolling.

**Comment by glacambre** [comment]
Another solution could be to try to get rid of recursiveScroll. Maybe there's a better way to find if an element can be scrolled?

**Comment by bovine3dom** [comment]
I think we should just look at the Vimperator / Pentadactyl code. 

Scrolling on https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html works exactly as I would expect it to in Pale Moon + Pentadactyl.

**Comment by bovine3dom** [comment]
@glacambre, have you looked at https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/insertCSS ?

**Comment by glacambre** [comment]
Closing this as I really don't know how to move this forward besides re-implementing smooth scrolling ourselves (which could be done in an entirely different PR).

**Comment by bovine3dom** [comment]
:( thanks for giving it a go. (It's actually the most searched-for thing on the repository).

**Comment by bovine3dom** [comment]
@glacambre I just found https://github.com/iamdustan/smoothscroll by accident, maybe that could help? (You can force it to use its own implementation, which might be better).

**Comment by glacambre** [comment]
I'll see if their [isScrollable](https://github.com/iamdustan/smoothscroll/blob/8a19e81e17ba39efed1c8b48c7976e3702238105/src/smoothscroll.js#L145) function correctly detects if an element is scrollable in [recursiveScroll](https://github.com/cmcaine/tridactyl/blob/08c0fb08e88bf8a710d779f7dcf559e3a7f92a1d/src/excmds.ts#L561)  (I remember trying something similar but I could have done something wrong). If it does, I think we'll be able to just set the scroll-behavior CSS property to smooth as we originally tried.

**Pull request closed without merging**
