### PR TITLE
Update newtab.md

### PR DESCRIPTION
**Pull request by rscircus**
This newtab.md reflects the most recent changes, as of release 1.8.2.

Mainfeatures
* Link the FAQ
* Resort highlighted features in such a way, that the ramp up with Tridactyl is eased for newcomers
* Move the more techie stuff (new tab override) down

### CODE REVIEW

**Comment by rscircus** [comment]
With regard to https://github.com/cmcaine/tridactyl/issues/162 :blush:

**Comment by cmcaine** [comment]
Thank you very much for your contribution.

It is a *bit* more enthusiastic/friendly than Olie and I are comfortable
with.

If Mozilla allows localised versions maybe we can use this one for the
Americans and Italians and something a bit less exciting for the rest of us
:)

(I think we'll probably just edit this for a tone we're more comfortable
with)

We're sorry to spurn your contribution like this, but I'm sure you
understand that writing style is quite a personal thing.

**Comment by rscircus** [comment]
OK, I'll make it more German. :)

**Comment by rscircus** [comment]
@IsaacKhor - for sure, left the wrap behavior as it was, but can change that.

**Comment by rscircus** [comment]
@IsaacKhor - done: https://github.com/cmcaine/tridactyl/compare/master...rscircus:patch-1

**Pull request merged**
