### PR TITLE
commandline_frame.ts: Make <Space> put selected completion in cmdline

### PR DESCRIPTION
**Pull request by glacambre**
I think this fixes https://github.com/cmcaine/tridactyl/issues/224 .
I'm very impressed by how easy this was, kudos to the devs responsible for this code!

### CODE REVIEW

**Comment by bovine3dom** [comment]
This works well, but I am reluctant to merge it until there is a proper way to de-select a completion (my muscle memory mostly has taken to using <Space> for that purpose...).

We could just make it such that tab/s-tab cycles through the completions, there is an extra step at the end/beginning that is selects nothing.

Thanks!

**Comment by glacambre** [comment]
I tested this commit with all three kinds of completions and it seems to work, let me know if there's a bug I missed :)

**Comment by bovine3dom** [comment]
Minor bug - shift-tab to cycle through the options doesn't loop back around. Tab works as I expect.

**Comment by glacambre** [comment]
Thanks for catching this bug, I should have paid better attention to the behavior of `<S-Tab>`. It should be fixed now.

**Comment by bovine3dom** [comment]
This seems to append a space to the URL once it is selected, despite fillcmdline being told not to supply a space.

**Comment by glacambre** [comment]
@bovine3dom This is normal, the space comes from not calling `keyevent.preventDefault()`. In my opinion this behavior is what mimics Vimperator's/Pentadactyl's behavior the best.
Also, not adding a space would require pressing space twice when trying to input multiple completions (not that this is a feature currently supported but maybe it will be one day).
I assume Vimperator and Pentadactyl users who press `<Space>` and then want to edit the argument usually use `<C-w>` to delete the previous word rather than pressing `<Backspace>` multiple times. We don't currently have `<C-w>` but users can use `<C-Backspace>` which behaves just the same.

Leaving the space is what makes the most sense to me. Let me know if you disagree, I'll add the required `preventDefault()` calls to this PR.

**Pull request merged**
