### PR TITLE
container logic

### PR DESCRIPTION
**Pull request by antonva**
This is mainly a fix for the hint -b issue as well as adding some container logic to libwebext and openInNewTab.
As per discussion on matrix, I'm keeping the tabopen behaviour but behind a setting in the config.
Addresses #406

### CODE REVIEW

**Comment by bovine3dom** [comment]
Do not merge until b35ed85 is released onto the AMO.

**Comment by bovine3dom** [comment]
This works great, @antonva. Since it will be a while before I can merge this, would you like to have a go at implementing:
- changing the container of a tab via an excmd
   - updating help with an example of autocmds that do this automatically
- allowing `{,win,tab}open` to accept container arguments
- creating new identities via excmds?

Cheers.

**Comment by antonva** [comment]
Yeah, no problem at all. I had already started working on implementing the basic context identities api as excmds.
I'll keep you posted here.

**Comment by antonva** [comment]
Upon looking at the implementation of the multi account container addon from mozilla, there are some peculiarities as to how it deals with containers. I was expecting there to be a unique constraint on the combination of name, color and icon but there isn't. Meaning that it's impossible to address a container by anything but it's id.

I'm of the thought that there should be a unique constraint on all three even if we support containers that are managed elsewhere, in such that **containerCreate** and **containerUpdate** in our implementation would not allow you to create the exact same container with the only discernable difference (the cookieStoreId) being hidden from the end user. 

Case in point:
example

**Comment by bovine3dom** [comment]
The warning is out in the wild in version 1.11.0, so this is no longer blocked. : )

**Pull request merged**
