### PR TITLE
Add incrementurl command

### PR DESCRIPTION
**Pull request by johnbeard**
Increments the last number in a URL by a given step (positive or
negative)

Also includes a url_util helper module and some tests for it

Logic taken from vimperator browser.js:17

Any thoughts on keybindings for this? Vimperator uses C-a and C-x for increment and decrement, respectively, but modifiers can't be used in keybindings: #41 (yet?)

Also, should there be a way to open the inc/dec'd address in a new tab?

### CODE REVIEW

**Comment by bovine3dom** [comment]
How about ]] and [[:  if the "next" button check fails, call incrementurl? We can't currently use modifiers in normal mode, otherwise ^a and ^x would be ideal.

**Comment by johnbeard** [comment]
Sorry, I sneakily edited that bit in but didn't say so!

I'm not sure increment URL is really the same as click next, especially when you can have a count. Not all URL increments are necessarily a reaction to failing to find a next button.

How about a binding something like like `[]` and `][`, using the existing prefix `[` and `]` as a generic prefix for actions like this? 

Then maybe you could have `[O` (or whatever) be "put the number in the command line for editing, then interpolate into the URL on enter" and so on for other variants?

OTOH, Vimperator also used `g` as a prefix for things like going up a level with `gu` and going to parent on `gU`, so maybe `g[` is appropriate instead? Vimperator seems to mix within `g`, as `gU` is a URL mutator, but `gi` finds a page element, while `[[` and `[f` both find page elements.

**Comment by cmcaine** [comment]
Thanks for the high quality PR!

We'll have modifier keys soonish, so don't sweat too much about choosing a default bind... Though, personally, I find select all with C-a pretty useful, so I'm not sure that should be a default bind for this.

If you're interested in contributing again, we could do with `gu` and friends from vimperator. To make testing slightly less verbose, I wrote a tiny test_utils library in the keyseq branch that might be helpful.

**Comment by johnbeard** [comment]
Indeed, I never liked how Vimperator killed C-a for select all. 

Increment/decrement doesn't seem so common that it even deserves a "top-level" single letter binding, when nearly all of `[` and `g` prefixes (and others) are available.

I'm looking at 'gU`, with `gu` up next.

I'll had a look at the test utils, but when will that likely get merged? I wouldn't want to get in a tangle waiting for code in other branches, or stealing it and causing conflicts! Seems it might save a line or two, but TBH, I wasn't feeling overly hard-done by, it's already fairly terse for unit testing.

**Comment by cmcaine** [comment]
Agreed on the binds.

You can just steal that one file from the keyseq branch. There won't be conflicts unless either file is edited out of sync and they'll be easy to merge.

Command name should maybe be `urlincrement` so it's pseudo namespaced with the future url manipulation commands?

If you don't object, I'll pull this, change the name and add some default binds of `]c` and `[c`, c for count.

**Comment by johnbeard** [comment]
Yes, please pull away and make any changes you like!

Agree on the name change and bindings look good to me.

I'll look at incorporating the keyseq test stuff in the gu/U branch.

**Comment by bovine3dom** [comment]
Merged in eae9cd0dabc47129c73b81ac433c795fdf513f35. Sorry it took so long!

**Comment by gsbabil** [comment]
You may bind your own keys like the following:

```
:bind ,a urlincrement +1
:bind ,x urlincrement -1
```

**Pull request closed without merging**
