### PR TITLE
Merge input and insert mode

### PR DESCRIPTION
**Pull request by glacambre**
Merging input and insert mode is done by removing every occurence of the
input mode. Instead, where Tridactyl would enter input mode, it instead
now sets a "focusinput" boolean to true in Tridactyl's state. This
boolean is set to false every time the mode changes, no matter what mode
Tridactyl was previously in.

Having a separate boolean instead of a mode requires separate handling
in both keydown_content.ts (for key suppression) and
parsers/insertmode.ts (for actually calling `focusinput` when Tab is
pressed).

This fixes half of https://github.com/cmcaine/tridactyl/issues/455
(__ being inserted in textareas on github).
The bug happened because modeSpecificSuppression() was only called when
state.mode was "input" and the cursor wasn't in a isTextEditable
element. It is fixed by making the call to modeSpecificSuppression
unconditional.

### CODE REVIEW

**Comment by bovine3dom** [comment]
I can confirm that this fixes __ being inserted, but it seems to make `gi` pretty unreliable on this page. If I reload the page the mode indicator sometimes displays insert mode, and `gi`/`g;` stop working.

Could you look into it?

**Comment by glacambre** [comment]
I managed to reproduce this issue once but then I reloaded Tridactyl and it disappeared. Can you manage to reliably reproduce it and if yes, what are the exact steps you take in order to do that?

Also, if I can't manage to fix this PR quickly I think we could just remove the if here:
https://github.com/cmcaine/tridactyl/blob/04bf9b737b66c7f8e317031ec57d5159dcd0142b/src/keydown_content.ts#L13 in order to fix #455.

**Comment by glacambre** [comment]
I found a way to reliably reproduce it. Investigating.

**Comment by cmcaine** [comment]
Please don't merge this until I've looked at it.

**Comment by glacambre** [comment]
Actually I can reproduce this bug even on master… To reproduce, visit https://github.com/cmcaine/tridactyl/pull/463 . Press <kbd>g</kbd><kbd>i</kbd> and then <kbd>Tab</kbd> until you reach the comment textarea. Then press <kbd>Esc</kbd>. Press <kbd>f</kbd> and whatever letter you need to press to follow the hint for the Pull requests page. Press <kbd>f</kbd> and whatever letter you need to press in order to come back to https://github.com/cmcaine/tridactyl/pull/463. Press <kbd>g</kbd><kbd>i</kbd>, you'll see that you can't enter insert mode.

I think the issue is that `focusinput()` keeps a reference to an element that could be removed from the page.

**Comment by glacambre** [comment]
I think 18ebe62 fixes this.

**Comment by glacambre** [comment]
@cmcaine This PR's aim was to fix https://github.com/cmcaine/tridactyl/issues/455 . Feel free to close it now that you fixed #455 :)

**Comment by bovine3dom** [comment]
Thanks, glacambre.

**Comment by glacambre** [comment]
You're welcome :)

I believe the fix included in 18ebe62 might still be worth including in master though.

**Pull request closed without merging**
