### PR TITLE
Expose scrollto, add winopen, pin and tabmove

### PR DESCRIPTION
**Pull request by Koushien**
The tabmove function could be made more concise, I'm sure, but initializing m to -1 did not have the desired effect of no arguments being passed -> moving tab to last in index.

### CODE REVIEW

**Comment by cmcaine** [comment]
All of these scroll functions are kind of messy. We should just have scrollby, scrollbylines, scrollbypages (a version that accepts real numbers), and scrollTo (version that accepts a % or a tuple of pixel values).

The up/down variants can die: let's rename the down one to be the normal one and remove the up one. We can just pass +ve or -ve values.

Counts won't work properly from normal mode, but it's something I'll get to.

**Comment by cmcaine** [comment]
Similarly scrolltotop/bottom should die: they're just parameterised versions of the scrollto variant I suggested above...

**Comment by bovine3dom** [comment]
> real numbers

Rational numbers are probably a better bet.

**Comment by cmcaine** [comment]
ScrollTo(π) is required for my workflow.

**Comment by Koushien** [comment]
>scrollTo (version that accepts a % or a tuple of pixel values)

Would that be % of total document height? No idea how to get that.

**Comment by cmcaine** [comment]
window.document.scrollHeight in content script.

**Comment by cmcaine** [comment]
Fixed in eb06c64be3f6825a663aa5c49cc38b8e0a782ebb

**Pull request merged**
