### PR TITLE
Fix #235

### LINKED ISSUE #235: :set newtab foo.bar/page.html to also change other newtab actions
When setting newtab parameter to foo.bar/page.html I observe the following behavior:
- [ :tabopen ] + [ enter ] open the correct foo.bar/page.html
- [ :open ] + [ enter ] open foo.bar/undefined.html
- [ clic on newtab ] still open the Tridactyl new tab page

I confirm that my main firefox newpage setting is set to foo.bar/page.html

Is this the expected behavior ?
If not, how complex are the required changes ?

Many thanks, Thibaut.

### PR DESCRIPTION
**Pull request by glacambre**
This fixes https://github.com/cmcaine/tridactyl/issues/235 by implementing the changes suggested by bovine3dom.

### CODE REVIEW

**Comment by bovine3dom** [comment]
This doesn't seem to work for me. Reproduce with `set newtab news.bbc.co.uk`. `tabopen` opens it; `open` opens Tridactyl new tab page.

My recommendation would be to make some JS that is hard coded into the newtab page to ensure that it runs whenever that page loads.

**Comment by glacambre** [comment]
This is weird, it works on my end, even with a fresh profile. Which Firefox version are you running? Does it also happen with a fresh profile? If so, could you upload a tarred empty profile so that I can try to reproduce this bug? I have no idea how to debug this and the code looks correct to me :\
I'm already doing the hard-coding thing (see https://github.com/cmcaine/tridactyl/pull/323/commits/1701b7e7fe6253a5bc8ec50d0ce5f97d19b0414a ). You can trigger this code path by opening a new tab using <C-t> or clicking on the "+" in the tab bar. Unfortunately, newtab.html flashes for a second before the actual newtab is loaded, hence my modification of the `open()` function.

**Comment by bovine3dom** [comment]
I'm on Firefox 57; I'll update and see if that fixes it.

**Comment by bovine3dom** [comment]
It works on FF58, so I've merged it :)

**Comment by cmcaine** [comment]
Is this inline JS? Could be a CSP issue for <58 if so.

**Comment by glacambre** [comment]
@cmcaine No, everything's done in either excmd.ts's `open()` (much like the way it's done in `tabopen()`) or at the end of `content.ts`.

**Comment by glacambre** [comment]
If this PR doesn't work for Firefox 57, should `strict_min_version` in manifest.json be set to `58.0`?
It's perfectly fine if you prefer reverting this PR and maintaining compatibility with older Firefox versions, although I believe Tridactyl currently uses several APIs that weren't available for Firefox 54.

**Comment by bovine3dom** [comment]
Nah, it's such a minor bug that I doubt anyone will notice. It's not like the add-on ceases to work at all.

**Pull request merged**
